version: 0.2

env:
  variables:
    #Update this with your Beanstalk URL when you are ready to connect your Frontend + Backend in step 3.8. Dont include the "/" at the end of the URL
    REACT_APP_API_BASE_URL: "http://{beanstalk-backend}.elasticbeanstalk.com"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Building React app...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
